In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [4]:
type(my_list)

list

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,5)) # tuple (rows,columns)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(1) # returns array with N numbers from 0 to 1 [0,1)

array([0.73568707])

In [21]:
np.random.rand(5,2)

array([[0.81607823, 0.72103888],
       [0.92262483, 0.18702302],
       [0.69696392, 0.45943471],
       [0.12805749, 0.54651525],
       [0.86942748, 0.277836  ]])

In [23]:
np.random.randn(10)

array([ 2.4426618 ,  0.87177996, -0.64678528,  1.34364938,  0.19392312,
        1.98725525,  1.40844473,  0.44977038,  0.45978445, -0.04012118])

In [25]:
np.random.rand(2,3)

array([[0.7874639 , 0.00921679, 0.40128933],
       [0.45628958, 0.49765931, 0.65483839]])

In [26]:
np.random.randint(0,101,(4,5))

array([[40, 45, 82, 42, 49],
       [46, 78, 54, 91, 93],
       [27, 11, 35, 51,  5],
       [95,  7, 24, 33, 50]])

In [30]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
np.random.rand(4)

array([0.59241457, 0.04645041, 0.60754485, 0.17052412])

In [45]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
 arr.shape

(25,)

In [42]:
arr = arr.reshape(5,5)

In [44]:
arr.shape

(5, 5)

array([0])