In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [8]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
arr / arr

<ipython-input-10-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1 / arr

<ipython-input-11-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.sin(3)

0.1411200080598672

In [15]:
arr.sum()

45

In [17]:
arr.mean()

4.5

In [18]:
arr.std()

2.8722813232690143

In [19]:
arr.var()

8.25

In [22]:
arr_2d = np.arange(0,25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr_2d.sum()

300

In [26]:
arr_2d.shape

(5, 5)

In [24]:
arr_2d.sum(axis=0) # across raws; shape (raws,columns)

array([50, 55, 60, 65, 70])

In [25]:
arr_2d.sum(axis=1) # across columns; shape (raws,columns)

array([ 10,  35,  60,  85, 110])